version: 0.0
os: linux
files:
  - source: target/cicd-0.0.1-SNAPSHOT.jar
    destination: ec2-65-0-31-120.ap-south-1.compute.amazonaws.com
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 180
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_application.sh
      timeout: 180
      runas: ec2-user
