version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/www
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 180
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_application.sh
      timeout: 180
      runas: ec2-user
