version: 0.2

phases:
  install:
    runtime-versions:
      java: 17
  pre_build:
    commands:
      - echo "Installing Maven..."
      - apt-get -y update
      - apt-get -y install maven
  build:
    commands:
      - echo "Building with Maven..."
      - mvn -B package --file pom.xml
