version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Installing Maven..."
      - apt-get -y update
      - apt-get -y install maven
  build:
    commands:
      - echo "Building with Maven..."
      - mvn -B package --file pom.xml
  post_build:
    commands:
      - echo "Pushing artifacts to S3 bucket..."
      - aws s3 cp target/cicd-0.0.1-SNAPSHOT.jar s3://pipeline-205/
